In [1]:
# download the kaggle titanic data set

# import train.csv
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
labels = df['Survived']
print(labels)

import tensorflow as tf
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Define the features and target variable
features = df[['Pclass', 'Sex', 'SibSp', 'Parch']]
target = df['Survived']

# Convert categorical variables to numerical
features['Sex'] = features['Sex'].map({'male': 0, 'female': 1})

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Create the random forest classifier
rf_classifier = RandomForestClassifier()

# Train the classifier
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
predictions = rf_classifier.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64
Accuracy: 0.7821229050279329

/var/folders/6v/v631xqn50t3dl170t0r4zcwm0000gn/T/ipykernel_70217/453239022.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['Sex'] = features['Sex'].map({'male': 0, 'female': 1})

In [13]:
import tensorflow_decision_forests as tfdf

# Define the features and target variable
features = df[['Pclass', 'Sex', 'SibSp', 'Parch', 'Survived']]
target = df['Survived']

# Convert categorical variables to numerical
features['Sex'] = features['Sex'].map({'male': 0, 'female': 1})
print(features)

# Create a TensorFlow dataset
dataset = tfdf.keras.pd_dataframe_to_tf_dataset(features, 'Survived', task=tfdf.keras.Task.CLASSIFICATION, max_num_classes=2)

# Define the model
model = tfdf.keras.RandomForestModel(task=tfdf.keras.Task.CLASSIFICATION)

# Train the model
model.fit(dataset)

# Make predictions on the test set
predictions = model.predict(dataset)

# Calculate the accuracy of the model
results = df['Survived']


print(results)

# accuracy = tfdf.keras.metrics.accuracy(target, predictions)
# print("Accuracy:", accuracy)

/var/folders/6v/v631xqn50t3dl170t0r4zcwm0000gn/T/ipykernel_70217/3642751908.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['Sex'] = features['Sex'].map({'male': 0, 'female': 1})

     Pclass  Sex  SibSp  Parch  Survived
0         3    0      1      0         0
1         1    1      1      0         1
2         3    1      0      0         1
3         1    1      1      0         1
4         3    0      0      0         0
..      ...  ...    ...    ...       ...
886       2    0      0      0         0
887       1    1      0      0         1
888       3    1      1      2         0
889       1    0      0      0         1
890       3    0      0      0         0

[891 rows x 5 columns]
Use /var/folders/6v/v631xqn50t3dl170t0r4zcwm0000gn/T/tmpq2bsvhvg as temporary training directory
Reading training dataset...
Training dataset read in 0:00:00.158692. Found 891 examples.
Training model...
Model trained in 0:00:00.068402
Compiling model...
Model compiled.
1/1 [==============================] - 0s 46ms/step
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

[INFO 24-01-18 23:45:14.4938 AEDT kernel.cc:1233] Loading model from path /var/folders/6v/v631xqn50t3dl170t0r4zcwm0000gn/T/tmpq2bsvhvg/model/ with prefix ae425a814736413e
[INFO 24-01-18 23:45:14.5181 AEDT decision_forest.cc:660] Model loaded with 300 root(s), 19034 node(s), and 4 input feature(s).
[INFO 24-01-18 23:45:14.5181 AEDT abstract_model.cc:1344] Engine "RandomForestOptPred" built
[INFO 24-01-18 23:45:14.5182 AEDT kernel.cc:1061] Use fast generic engine

In [22]:
comparisonDF = df[['Survived']].copy()
comparisonDF['Predictions'] = predictions

comparisonDF['Predictions'] = comparisonDF['Predictions'].apply(lambda x: 1 if x > 0.5 else 0)

# count how many rows where survived is different from predictions
count_different = (comparisonDF['Survived'] != comparisonDF['Predictions']).sum()
print("Count of rows where 'Survived' is different from 'Predictions':", count_different)
print("total rows: ", len(comparisonDF))


# insert predictions as a "prediction" column in survived_copy

# survived_copy['prediction'] = predictions

Count of rows where 'Survived' is different from 'Predictions': 168
total rows:  891